(() => {
  'use strict';
  const TAU=Math.PI*2, clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const v3=(x=0,y=0,z=0)=>[x,y,z], sub=(a,b)=>v3(a[0]-b[0],a[1]-b[1],a[2]-b[2]), dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2], cross=(a,b)=>v3(a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]), norm=a=>{const n=Math.hypot(...a)||1;return v3(a[0]/n,a[1]/n,a[2]/n)};
  const mat={
    multiply(a,b){const r=new Float32Array(16);for(let c=0;c<4;c++)for(let row=0;row<4;row++)r[c*4+row]=a[row]*b[c*4]+a[4+row]*b[c*4+1]+a[8+row]*b[c*4+2]+a[12+row]*b[c*4+3];return r},
    perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0])},
    lookAt(eye,target,up){const z=norm(sub(eye,target)),x=norm(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1])},
    inverse(a){const o=new Float32Array(16),b00=a[0]*a[5]-a[1]*a[4],b01=a[0]*a[6]-a[2]*a[4],b02=a[0]*a[7]-a[3]*a[4],b03=a[1]*a[6]-a[2]*a[5],b04=a[1]*a[7]-a[3]*a[5],b05=a[2]*a[7]-a[3]*a[6],b06=a[8]*a[13]-a[9]*a[12],b07=a[8]*a[14]-a[10]*a[12],b08=a[8]*a[15]-a[11]*a[12],b09=a[9]*a[14]-a[10]*a[13],b10=a[9]*a[15]-a[11]*a[13],b11=a[10]*a[15]-a[11]*a[14],det=b00*b11-b01*b10+b02*b09+b03*b08-b04*b07+b05*b06;if(!det)return null;const d=1/det;o[0]=(a[5]*b11-a[6]*b10+a[7]*b09)*d;o[1]=(a[2]*b10-a[1]*b11-a[3]*b09)*d;o[2]=(a[13]*b05-a[14]*b04+a[15]*b03)*d;o[3]=(a[10]*b04-a[9]*b05-a[11]*b03)*d;o[4]=(a[6]*b08-a[4]*b11-a[7]*b07)*d;o[5]=(a[0]*b11-a[2]*b08+a[3]*b07)*d;o[6]=(a[14]*b02-a[12]*b05-a[15]*b01)*d;o[7]=(a[8]*b05-a[10]*b02+a[11]*b01)*d;o[8]=(a[4]*b10-a[5]*b08+a[7]*b06)*d;o[9]=(a[1]*b08-a[0]*b10-a[3]*b06)*d;o[10]=(a[12]*b04-a[13]*b02+a[15]*b00)*d;o[11]=(a[9]*b02-a[8]*b04-a[11]*b00)*d;o[12]=(a[5]*b07-a[4]*b09-a[6]*b06)*d;o[13]=(a[0]*b09-a[1]*b07+a[2]*b06)*d;o[14]=(a[13]*b01-a[12]*b03-a[14]*b00)*d;o[15]=(a[8]*b03-a[9]*b01+a[10]*b00)*d;return o},
    point(m,p){const x=p[0],y=p[1],z=p[2],w=p[3]??1;return [m[0]*x+m[4]*y+m[8]*z+m[12]*w,m[1]*x+m[5]*y+m[9]*z+m[13]*w,m[2]*x+m[6]*y+m[10]*z+m[14]*w,m[3]*x+m[7]*y+m[11]*z+m[15]*w]}
  };
  const defaultCamera=()=>({targetX:0,targetZ:0,distance:12.5,yaw:.28,pitch:.54,fov:.78,version:2});
  class TabletopRenderer {
    constructor(canvas,callbacks={}){this.canvas=canvas;this.cb=callbacks;this.gl=canvas.getContext('webgl',{alpha:false,antialias:true});this.ready=!!this.gl;this.camera=defaultCamera();this.board={width:16,depth:10,thickness:.28};this.crop={left:0,top:0,right:1,bottom:1};this.tokens=[];this.textureCache=new Map();this.drag=null;this.cameraChanged=false;if(!this.ready){callbacks.onError?.('WebGL não está disponível neste navegador.');return}this.init();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas);canvas.addEventListener('pointerup',event=>this.finishTokenDrag(event));canvas.addEventListener('pointercancel',event=>this.finishTokenDrag(event));this.bindInput();canvas.addEventListener('pointerdown',event=>this.captureGrabOffset(event));canvas.addEventListener('pointermove',event=>this.reportTokenDrag(event));this.resize()}
    init(){const gl=this.gl;const texturedVS='attribute vec3 p;attribute vec2 uv;uniform mat4 mvp;varying vec2 vuv;void main(){vuv=uv;gl_Position=mvp*vec4(p,1.0);}';const texturedFS='precision mediump float;uniform sampler2D tex;uniform vec4 tint;varying vec2 vuv;void main(){vec4 c=texture2D(tex,vuv)*tint;if(c.a<0.07)discard;gl_FragColor=c;}';const solidVS='attribute vec3 p;uniform mat4 mvp;void main(){gl_Position=mvp*vec4(p,1.0);}';const solidFS='precision mediump float;uniform vec4 color;void main(){gl_FragColor=color;}';const shadowFS='precision mediump float;varying vec2 vuv;void main(){float d=distance(vuv,vec2(.5));float a=smoothstep(.5,.08,d)*.34;gl_FragColor=vec4(0.,0.,0.,a);}';this.textured=this.program(texturedVS,texturedFS,true);this.solid=this.program(solidVS,solidFS,false);this.shadow=this.program(texturedVS,shadowFS,true);this.vbo=gl.createBuffer();this.ibo=gl.createBuffer();this.white=this.textureFromPixels(new Uint8Array([255,255,255,255]),1,1);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.clearColor(.025,.022,.03,1)}
    program(vs,fs,uv){const gl=this.gl,compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(shader));return shader},program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));return{program,p:gl.getAttribLocation(program,'p'),uv:uv?gl.getAttribLocation(program,'uv'):-1,mvp:gl.getUniformLocation(program,'mvp'),tex:uv?gl.getUniformLocation(program,'tex'):null,tint:gl.getUniformLocation(program,uv?'tint':'color')}}
    textureFromPixels(data,w,h){const gl=this.gl,t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,data);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t}
    texture(url){if(!url)return Promise.resolve(this.white);if(this.textureCache.has(url))return this.textureCache.get(url);const promise=new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const gl=this.gl,t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);resolve({texture:t,aspect:image.naturalWidth/image.naturalHeight||.7})};image.onerror=reject;image.src=url});this.textureCache.set(url,promise);return promise}
    contentBounds(image){if(!image?.naturalWidth||!image?.naturalHeight)return{left:0,top:0,right:1,bottom:1};try{const longest=640,scale=Math.min(1,longest/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas'),context=canvas.getContext('2d',{willReadFrequently:true});canvas.width=width;canvas.height=height;context.drawImage(image,0,0,width,height);const pixels=context.getImageData(0,0,width,height).data;let left=width,top=height,right=-1,bottom=-1;for(let y=0;y<height;y+=2)for(let x=0;x<width;x+=2){const index=(y*width+x)*4,brightness=pixels[index]+pixels[index+1]+pixels[index+2];if(pixels[index+3]>24&&brightness>38){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y)}}if(right<left||bottom<top)return{left:0,top:0,right:1,bottom:1};const padding=5;return{left:Math.max(0,(left-padding)/width),top:Math.max(0,(top-padding)/height),right:Math.min(1,(right+padding)/width),bottom:Math.min(1,(bottom+padding)/height)}}catch(error){return{left:0,top:0,right:1,bottom:1}}}
    textureFromImage(image){const gl=this.gl,maxSize=Math.min(gl.getParameter(gl.MAX_TEXTURE_SIZE)||4096,4096),ratio=Math.min(1,maxSize/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*ratio)),height=Math.max(1,Math.round(image.naturalHeight*ratio)),source=document.createElement('canvas'),context=source.getContext('2d');source.width=width;source.height=height;context.drawImage(image,0,0,width,height);const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,source);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return{texture,aspect:image.naturalWidth/image.naturalHeight||.7}}
    async setMap(url,image){if(!url||!image?.naturalWidth)return false;try{const loaded=this.textureFromImage(image);this.mapTexture=loaded.texture;this.crop=this.contentBounds(image);const cropWidth=this.crop.right-this.crop.left,cropHeight=this.crop.bottom-this.crop.top,aspect=image.naturalWidth*cropWidth/(image.naturalHeight*cropHeight);this.board.width=16;this.board.depth=16/aspect;this.render();return true}catch(error){console.error('Falha ao enviar o mapa para o WebGL.',error);this.cb.onError?.('Não foi possível renderizar o mapa 3D.');return false}}
    async setTokens(tokens){const hydrated=await Promise.all(tokens.map(async token=>({...token,...await this.texture(token.url)}))),dragged=this.drag?.kind==='token'?this.drag.token:null;if(dragged){const replacement=hydrated.find(token=>token.id===dragged.id);if(replacement){replacement.x=dragged.x;replacement.y=dragged.y;this.drag.token=replacement}}this.tokens=hydrated;this.render()}
    setState(scene){this.scene=scene;if(!scene)return;if(!scene.tableCamera||scene.tableCamera.version!==2)scene.tableCamera=defaultCamera();Object.assign(this.camera,scene.tableCamera);this.render()}
    resize(){const ratio=Math.min(devicePixelRatio||1,2),r=this.canvas.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*ratio)),h=Math.max(1,Math.round(r.height*ratio));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h)}this.render()}
    cameraMatrices(){const c=this.camera,cp=Math.cos(c.pitch),eye=[c.targetX+c.distance*cp*Math.sin(c.yaw),c.distance*Math.sin(c.pitch),c.targetZ+c.distance*cp*Math.cos(c.yaw)],view=mat.lookAt(eye,[c.targetX,0,c.targetZ],[0,1,0]),projection=mat.perspective(c.fov,this.canvas.width/this.canvas.height,.05,100);return{eye,view,projection,mvp:mat.multiply(projection,view)}}
    normalizedToWorld(point){const crop=this.crop||{left:0,top:0,right:1,bottom:1},x=(point.x-crop.left)/(crop.right-crop.left),y=(point.y-crop.top)/(crop.bottom-crop.top);return{x:(x-.5)*this.board.width,z:(y-.5)*this.board.depth}}
    worldToNormalized(point){const crop=this.crop||{left:0,top:0,right:1,bottom:1},x=point.x/this.board.width+.5,y=point.z/this.board.depth+.5;return{x:clamp(crop.left+x*(crop.right-crop.left),0,1),y:clamp(crop.top+y*(crop.bottom-crop.top),0,1)}}
    render(){if(!this.ready||!this.scene||!this.mapTexture)return;const gl=this.gl,{mvp}=this.cameraMatrices(),crop=this.crop||{left:0,top:0,right:1,bottom:1};gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.drawBox(mvp);this.drawQuad(mvp,[-this.board.width/2,0,-this.board.depth/2,crop.left,crop.top,-this.board.width/2,0,this.board.depth/2,crop.left,crop.bottom,this.board.width/2,0,this.board.depth/2,crop.right,crop.bottom,this.board.width/2,0,-this.board.depth/2,crop.right,crop.top],this.mapTexture,[1,1,1,1]);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);this.tokens.forEach(token=>this.drawShadow(mvp,token));gl.depthMask(true);this.tokens.forEach(token=>this.drawBillboard(mvp,token));gl.disable(gl.BLEND)}
    drawBox(mvp){const w=this.board.width/2,d=this.board.depth/2,t=-this.board.thickness,vertices=[-w,0,-d,w,0,-d,w,0,d,-w,0,d,-w,t,-d,w,t,-d,w,t,d,-w,t,d],indices=[4,5,1,4,1,0,5,6,2,5,2,1,6,7,3,6,3,2,7,4,0,7,0,3];this.drawSolid(mvp,vertices,indices,[.09,.075,.07,1])}
    drawShadow(mvp,token){const p=this.normalizedToWorld(token),h=(token.scale||110)/110*2.6,w=h*.45,d=h*.16,y=.014,verts=[p.x-w,y,p.z-d,0,0,p.x-w,y,p.z+d,0,1,p.x+w,y,p.z+d,1,1,p.x+w,y,p.z-d,1,0];this.drawQuad(mvp,verts,this.white,[1,1,1,1],this.shadow)}
    drawBillboard(mvp,token){const p=this.normalizedToWorld(token),height=(token.scale||110)/110*2.6,width=height*(token.aspect||.7),right=[Math.cos(this.camera.yaw),0,-Math.sin(this.camera.yaw)],x0=p.x-right[0]*width/2,z0=p.z-right[2]*width/2,x1=p.x+right[0]*width/2,z1=p.z+right[2]*width/2,verts=[x0,.025,z0,0,1,x1,.025,z1,1,1,x1,height+.025,z1,1,0,x0,height+.025,z0,0,0];this.drawQuad(mvp,verts,token.texture,token.selected?[1.12,1.02,.78,1]:[1,1,1,1])}
    drawQuad(mvp,vertices,texture,tint,program=this.textured){const gl=this.gl;gl.useProgram(program.program);gl.bindBuffer(gl.ARRAY_BUFFER,this.vbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(program.p);gl.vertexAttribPointer(program.p,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(program.uv);gl.vertexAttribPointer(program.uv,2,gl.FLOAT,false,20,12);gl.uniformMatrix4fv(program.mvp,false,mvp);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(program.tex,0);if(program.tint)gl.uniform4fv(program.tint,tint);gl.drawArrays(gl.TRIANGLE_FAN,0,4)}
    drawSolid(mvp,vertices,indices,color){const gl=this.gl,p=this.solid;gl.useProgram(p.program);gl.bindBuffer(gl.ARRAY_BUFFER,this.vbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(p.p);gl.vertexAttribPointer(p.p,3,gl.FLOAT,false,12,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.ibo);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(indices),gl.DYNAMIC_DRAW);gl.uniformMatrix4fv(p.mvp,false,mvp);gl.uniform4fv(p.tint,color);gl.drawElements(gl.TRIANGLES,indices.length,gl.UNSIGNED_SHORT,0)}
    ray(clientX,clientY){const rect=this.canvas.getBoundingClientRect(),x=(clientX-rect.left)/rect.width*2-1,y=1-(clientY-rect.top)/rect.height*2,{mvp,eye}=this.cameraMatrices(),inverse=mat.inverse(mvp);if(!inverse)return null;const near=mat.point(inverse,[x,y,-1,1]),far=mat.point(inverse,[x,y,1,1]),n=v3(near[0]/near[3],near[1]/near[3],near[2]/near[3]),f=v3(far[0]/far[3],far[1]/far[3],far[2]/far[3]);return{origin:eye,direction:norm(sub(f,n))}}
    screenToBoard(clientX,clientY){const ray=this.ray(clientX,clientY);if(!ray||Math.abs(ray.direction[1])<.0001)return null;const t=-ray.origin[1]/ray.direction[1];if(t<0)return null;const hit=v3(ray.origin[0]+ray.direction[0]*t,0,ray.origin[2]+ray.direction[2]*t);if(Math.abs(hit[0])>this.board.width/2||Math.abs(hit[2])>this.board.depth/2)return null;if(this.drag?.kind==='token'&&this.drag.grabOffset){hit[0]+=this.drag.grabOffset.x;hit[2]+=this.drag.grabOffset.z}return this.worldToNormalized({x:hit[0],z:hit[2]})}
    pick(clientX,clientY){const ray=this.ray(clientX,clientY);if(!ray)return null;let selected=null,best=Infinity;this.tokens.forEach(token=>{const p=this.normalizedToWorld(token),height=(token.scale||110)/110*2.6,width=height*(token.aspect||.7),normal=norm([Math.sin(this.camera.yaw),0,Math.cos(this.camera.yaw)]),den=dot(ray.direction,normal);if(Math.abs(den)<.0001)return;const t=dot(sub([p.x,.025,p.z],ray.origin),normal)/den;if(t<0||t>=best)return;const hit=v3(ray.origin[0]+ray.direction[0]*t,ray.origin[1]+ray.direction[1]*t,ray.origin[2]+ray.direction[2]*t),right=[Math.cos(this.camera.yaw),0,-Math.sin(this.camera.yaw)],across=dot(sub(hit,[p.x,.025,p.z]),right);if(Math.abs(across)<=width/2&&hit[1]>=.025&&hit[1]<=height+.025){selected=token;best=t}});return selected}
    bindInput(){const c=this.canvas;c.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('wheel',e=>{e.preventDefault();e.stopPropagation();this.camera.distance=clamp(this.camera.distance*(e.deltaY>0?1.09:.91),5,42);this.changed()},{passive:false});c.addEventListener('pointerdown',e=>{e.stopPropagation();c.setPointerCapture(e.pointerId);const token=e.button===0?this.pick(e.clientX,e.clientY):null;if(token){this.drag={kind:'token',token,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,moved:false};return}if(e.button===0&&this.cb.shouldPlace?.()){const point=this.screenToBoard(e.clientX,e.clientY);if(point)this.cb.onPlace?.(point);return}this.drag={kind:e.button===2||e.altKey?'orbit':'pan',x:e.clientX,y:e.clientY,pointerId:e.pointerId}});c.addEventListener('pointermove',e=>{if(!this.drag||this.drag.pointerId!==e.pointerId)return;e.stopPropagation();if(this.drag.kind==='token'){if(!this.drag.moved&&Math.hypot(e.clientX-this.drag.startX,e.clientY-this.drag.startY)>3){this.drag.moved=true;this.cb.onTokenDragStart?.(this.drag.token.id,e.clientX,e.clientY)}const point=this.screenToBoard(e.clientX,e.clientY);if(point){this.drag.token.x=point.x;this.drag.token.y=point.y;this.cb.onTokenMove?.(this.drag.token.id,point);this.render()}}else{const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;this.drag.x=e.clientX;this.drag.y=e.clientY;if(this.drag.kind==='orbit'){this.camera.yaw=(this.camera.yaw-dx*.008+TAU)%TAU;this.camera.pitch=clamp(this.camera.pitch+dy*.007,.28,1.25)}else{const speed=this.camera.distance*.0025,right=[Math.cos(this.camera.yaw),-Math.sin(this.camera.yaw)],forward=[Math.sin(this.camera.yaw),Math.cos(this.camera.yaw)];this.camera.targetX+=(dx*right[0]-dy*forward[0])*speed;this.camera.targetZ+=(dx*right[1]-dy*forward[1])*speed}this.changed()}});c.addEventListener('pointerup',e=>{if(this.drag?.pointerId!==e.pointerId)return;const drag=this.drag;this.drag=null;if(drag.kind==='token'&&!drag.moved)this.cb.onSelect?.(drag.token.id);this.cb.onInteractionEnd?.()})}
    captureGrabOffset(event){if(event.button!==0||this.drag?.kind!=='token')return;const point=this.screenToBoard(event.clientX,event.clientY);if(!point)return;const token=this.normalizedToWorld(this.drag.token),ground=this.normalizedToWorld(point);this.drag.grabOffset={x:token.x-ground.x,z:token.z-ground.z}}
    reportTokenDrag(event){if(this.drag?.kind==='token'&&this.drag.pointerId===event.pointerId)this.cb.onTokenDrag?.(this.drag.token.id,event.clientX,event.clientY)}
    finishTokenDrag(event){if(this.drag?.kind==='token'&&this.drag.pointerId===event.pointerId&&this.drag.moved)this.cb.onTokenDragEnd?.(this.drag.token.id,event.clientX,event.clientY)}
    changed(){if(this.scene)this.scene.tableCamera={...this.camera};this.cb.onCameraChange?.({...this.camera});this.render()}
    zoomBy(step){this.camera.distance=clamp(this.camera.distance-step,5,42);this.changed()}
    panScreen(rightAmount,upAmount){const right=[Math.cos(this.camera.yaw),-Math.sin(this.camera.yaw)],up=[-Math.sin(this.camera.yaw),-Math.cos(this.camera.yaw)];this.camera.targetX+=right[0]*rightAmount+up[0]*upAmount;this.camera.targetZ+=right[1]*rightAmount+up[1]*upAmount;this.changed()}
    resetCamera(){Object.assign(this.camera,defaultCamera());this.changed()}
    focusNormalized(point){const world=this.normalizedToWorld(point);this.camera.targetX=world.x;this.camera.targetZ=world.z;this.changed()}
    destroy(){this.resizeObserver?.disconnect();this.textureCache.clear()}
  }
  window.TabletopRenderer=TabletopRenderer;window.TabletopCameraDefaults=defaultCamera;
})();
